### ISSUE TITLE
Backdoor in Beds Protector

### ISSUE THREAD

**Issue by JosepBalague** [NotPrab/.NET-Obfuscator#18]
Hi,

Windows Defender reports Backdoor:Win32/Bladabindi!ml in Beds Protector bin.rar downloaded today. Tested in 3 PC and all same results:

[https://github.com/BedTheGod/ConfuserEx-Mod-By-Bed/issues/60](https://github.com/BedTheGod/ConfuserEx-Mod-By-Bed/issues/60)

Thanks

**Comment by NotPrab** [comment]
seems to be fixed
